
# Config file for Kymata Dataset 4.00

# General
data_location: "cbu"                # local | cbu | cbu-local
dataset_directory_name: "dataset_4-english-narratives"
mri_structurals_directory: "raw_mri_structurals"


# General information related to the dataset
list_of_participants: [
                        "participant_01"
                        ]
input_streams: [
                    "auditory"
                ]                    # auditory | visual
number_of_runs: 4                    # number of runs
repetitions_per_runs: 2              # number of repetitions per run
number_of_trials: 400                # number of trials
mri_structural_type: "T1"            # T1 | flash

# Preprocessing pipeline
emeg_machine_used_to_record_data: 'triux'
skip_maxfilter_if_previous_runs_exist: True
skip_ica_if_previous_runs_exist: True
remove_VEOH_and_HEOG: True
remove_ECG: True
automatic_bad_channel_detection_requested: False
supress_excessive_plots_and_prompts: True

# Inverse operator
eeg: True
meg: True

# Method to estimate noise covariance matrix
cov_method: 'fusion'               # grandave | emptyroom | runstart | fusion
duration:                          # in seconds for the duration of the empty room condition used, can be None for whole duration
reg_method:                        # None | 'auto'

# Creation of evoked trial pipeline
audio_delivery_latency:  26        # in milliseconds
visual_delivery_latency: 17        # in milliseconds
tactile_delivery_latency: 0        # in milliseconds
audio_delivery_shift_correction: 0.0005375   # in seconds per second
tmin: -0.2  # seconds
tmax: 1.8   # seconds

eeg_thresh: 1 #200e-6
grad_thresh: 1 #4000e-13
mag_thresh: 1 #4000e-15
