name: Assess Test Coverage

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # be sure to add this ref on your checkout
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11' # Define your project python version
      - id: run-tests
        uses: JotaFan/pycoverage@v1.0.0
        with:
          cov-omit-list: tests/*
          cov-threshold-single: 85
          cov-threshold-total: 90
          async-tests: true
          poetry-version: 1.4.2
          package-extras: dev,tests
          github_token: ${{ secrets.github_token }}
          working_branch: ${{ steps.extract_branch.outputs.branch }}
